### PR TITLE
Feat/drop down field#taskAQL05

### PR DESCRIPTION
**Pull request by nguyenphuochai1998**

### CODE REVIEW

**Review by nguyenphuochai1998 — COMMENTED** [review]
review fist check it ok

**Review by nguyenphuochai1998 — COMMENTED** [review]
review fist check it ok

**Review by nguyenphuochai1998 — COMMENTED** [review]
fist check it ok

**Review by NguyenQuangKhang — COMMENTED** [review]
config initial hint textStyle

**Review by NguyenQuangKhang — APPROVED** [review]

**Pull request closed without merging**
